package:
  name: cgns
  version: "3.3.0"

source:
  fn: v3.3.0.tar.gz
  url: https://github.com/CGNS/CGNS/archive/v3.3.0.tar.gz
  md5: 64e5e8d97144c1462bee9ea6b2a81d7f 

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - hdf5

  run:
   - python
   - hdf5


about:
  home: https://cgns.github.io/
  license: GPL
  summary: CFD General Notation System
  description: |
    This is a recommended standard storage practice by AIAA.
     The library is open-source and freely available.
  doc_url: https://cgns.github.io/CGNS_doc_current/index.html
  dev_url: https://cgns.github.io
