package:
  name: chlone
  version: "0.51"

source:
  path: ../CHLone-v0.51

build:
  number: 0

requirements:
  build:
   - python
   - scons
   - hdf5
   - cgns
   - numpy
   - cython
   - sphinx

  run:
   - python
   - hdf5
   - numpy

test:
  requires:
    - numpy

  imports:
    - CHLone

about:
  home: chlone.sourceforge.net
  license: BSD
  summary: CHLone is a CGNS/SIDS compliant mapping of SIDS-to-HDF5
