package:
  name: cassiopee_connector
  version: "2.3"

source:
  path: ../src/Connector

build:
  number: 0

requirements:
  build:
   - python
   - scons
   - hdf5
   - numpy
   - cython
   - cassiopee_kcore
   - cassiopee_converter

  run:
   - python
   - hdf5
   - numpy
   - cassiopee_kcore
   - cassiopee_converter
   - libpng

test:
  requires:
    - numpy
    - cassiopee_kcore
    - cassiopee_converter
    - libpng

  imports:
    - Connector
    - Connector.PyTree

about:
  home: elsa.onera.fr/Cassiopee
  license: GPLv3
  summary: Connector for *Cassiopee* modules.

