package:
  name: cassiopee_initiator
  version: "2.3"

source:
  path: ../src/Initiator

build:
  number: 0

requirements:
  build:
   - python
   - scons
   - hdf5
   - numpy
   - cython
   - cassiopee_kcore
   - cassiopee_converter

  run:
   - python
   - hdf5
   - numpy
   - cassiopee_kcore
   - cassiopee_converter
   - libpng

test:
  requires:
    - numpy
    - cassiopee_kcore
    - cassiopee_converter
    - libpng

  imports:
    - Initiator

about:
  home: elsa.onera.fr/Cassiopee
  license: GPLv3
  summary: Initiator for *Cassiopee* modules.

