package:
  name: vtk
  version: "7.1.0"

source:
  fn: VTK-7.1.0.tar.gz
  url: http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz
  sha1: d3701ff23cb935e107e00174cf75d45a7a9cbdda

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - hdf5
   - qt
   - mesa

  run:
   - python
   - hdf5
   - mesa

test:
  requires:
    - numpy
    - pillow

  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets


about:
  home: http://www.vtk.org/
  license: BSD
  summary: 3D computer graphics, image processing, and visualization
  description: |
    The Visualization Toolkit (VTK) is an open-source, freely available
    software system for 3D computer graphics, image processing, and
    visualization. It consists of a C++ class library and several interpreted
    interface layers including Tcl/Tk, Java, and Python.
  doc_url: http://www.vtk.org/documentation/
  dev_url: https://gitlab.kitware.com/vtk/vtk
