package:
  name: cassiopee_transform
  version: "2.3"

source:
  path: ../src/Transform

build:
  number: 0

requirements:
  build:
   - python
   - scons
   - hdf5
   - numpy
   - cython
   - cgns
   - libpng
   - cassiopee_kcore

  run:
   - python
   - hdf5
   - numpy
   - cassiopee_kcore

test:
  requires:
    - numpy
    - cassiopee_kcore
    - cassiopee_converter

  imports:
    - Transform
    - Transform.PyTree

about:
  home: elsa.onera.fr/Cassiopee
  license: GPLv3
  summary: Transformations of arrays/pyTrees for *Cassiopee* modules.

